version: "3"

services:

  maildev:
    image: maildev/maildev
    restart: always
    ports:
      - "1080:1080"
      - "587:587"
      - "1025:1025"
    environment:
      - EMAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=rosasuong.tech@gmail.com
      - MAIL_PASSWORD=uqqbjgeeffetravf
      - MAIL_STMP_AUTH=true
      - MAIL_STARTTLS_ENABLE=true
      - MAIL_STARTTLS_REQUIRED=true

  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data


    environment:
      - MONGO_INITDB_ROOT_USERNAME=hieu
      - MONGO_INITDB_ROOT_PASSWORD=hieu123

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=hieu
      - ME_CONFIG_MONGODB_ADMINPASSWORD=hieu123
      - ME_CONFIG_MONGODB_SERVER=mongodb

#  jenkins:
#    image: jenkins/jenkins:lts
#    container_name: jenkins
#    ports:
#      - "8080:8080"
#      - "50000:50000"
#    volumes:
#      - ~/jenkins:/var/jenkins_home
#      - /var/run/docker.sock:/var/run/docker.sock
#    environment:
#      JENKINS_OPTS: --httpPort=8080

  shopapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - maildev
      - mongo-express
    restart: always
    ports:
      - "8888:8080"
#    environment:
#      - SPRING_DATA_MONGODB_URI=mongodb://hieu:hieu123@mongodb:27017/ShopApp?authSource=admin

volumes:
  mongo: { }
