server:
  port: 8888
  servlet:
    context-path: /identity

spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: rosasuong.tech@gmail.com
    password: uqqbjgeeffetravf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  data:
    mongodb:
      database: ShopApp
      username: hieu
      password: hieu123
      port: 27017
      authentication-database: admin
#      host: mongodb

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

amazonProperties:
  endpointUrl: https://s3.us-east-1.amazonaws.com
  accessKey: AKIAVRUVSQ5OLR3PFKFL
  secretKey: 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
  bucketName: simplestoreservice

jwt:
  secretKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600    #insecond
  refresh-duration: 4600
