
server:
  port: 8083


spring:


  mail:
    host: smtp.gmail.com
    port: 587
    username: rosasuong.tech@gmail.com
    password: uqqbjgeeffetravf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  data:
    mongodb:
      database: ShopApp
      username: hieu
      password: hieu123
      port: 27017
      authentication-database: admin




  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

amazonProperties:
    endpointUrl: https://s3.us-east-1.amazonaws.com
    accessKey: AKIAVRUVSQ5OLR3PFKFL
    secretKey: 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
    bucketName: simplestoreservice
